### ISSUE TITLE
header footer pageset layout view etc.problem

### ISSUE THREAD

**Issue by liufeijin** [VSRonin/QtXlsxWriter#44] opened 2020-01-03 15:27 UTC
VSRonin
I have tried your branch of QtXlsxWriter and Qtexcel .
Both projects have problem  that the excel file will be damaged when written something to a exist file .The red mark will be lose in below PIC by QtXlsxWriter and Qtexcel 
![1](https://user-images.githubusercontent.com/19425403/71732235-b5901900-2e81-11ea-9d7b-07f2d7d32b4b.png)

I copy code from  projects QtXlsxWriter and Qtexcel and add some code also.
Now some bug are fixed .
I want to patch your project or QtExcel but failed many times.
So i made a new branch on https://github.com/liufeijin/littleQXlsx
below is the the test file and  my code zip file
[test.xlsx](https://github.com/VSRonin/QtXlsxWriter/files/4019661/test.xlsx)
[QXlsx.zip](https://github.com/VSRonin/QtXlsxWriter/files/4019664/QXlsx.zip)

if you have free time to patch your project , will be great!

**Comment by liufeijin** [comment] 2020-01-03 15:29
I don't know how to compare two project ,and to find the difference as i don't know how to use github.
I am green hand on coding .

**Comment by VSRonin** [comment] 2020-01-07 09:51
Duplicate of https://github.com/dbzhang800/QtXlsxWriter/issues/190

For new projects you should not adopt this library but instead use https://github.com/QtExcel/QXlsx

**Closed** 2020-01-07 09:52 UTC
Labels: duplicate
